site_name: 2020_5BI_Team5

nav:
    - 'Project Charter': 'charter01.md'
    - 'Software Requirements Specification': 'Software_Requirements_Specification.md'
    - 'Software Project Management Plan': 'project_management.md'
    - 'Test Case Specification': 'test_case_specification.md'
    - 'Business model canvas': 'business_model_canvas-team5.pdf'
    - 'Project model canvas': 'Project_Model_Canvas-team5.pdf'
    - 'Project Success Criteria': 'Project_Success_Criteria.md'
    - 'User Guide': 'User_Guide.pdf'
    - 'Architecture and design': 'Architecture_And_Design.md'
    - 'iteration plan': 'iteration_plan.md'
    - 'release plan': 'release_plan.md'
    - 'System Documentation': 'System_Documentation.md'
    - 'Memo of understanding': 'Memo_of_understanding.md'
    - 'Memo of understanding': 'Memo_of_understanding.pdf'
    - 'Release Plan': 'release_plan.pdf'
    - 'Iteration Plan': 'iteration_plan.pdf'
    - 'Project Success Criteria': 'Project_Success_Criteria.pdf'
    - 'Architecture and design': 'Architecture_And_Design.pdf'
    - 'Coding Standars': 'coding_standards.pdf'
    - 'Test Plan': 'test_plan.pdf'
    - 'Test Case Specification': 'test_case_specification.pdf'
    - 'System documentation': 'System_Documentation.pdf'



theme:
    name: readthedocs
