site_name: 2020_5BI_Team5

nav:
    - 'Project Charter': 'charter01.md'
    - 'Software Requirements Specification': 'Software_Requirements_Specification.md'
    - 'Software Project Management Plan': 'project_management.md'
    - 'Test Case Specification': 'test_case_specification.md'
    - 'Business model canvas' : 'business_model_canvas-team5.pdf'
    - 'Project model canvas' : 'Project_Model_Canvas-team5.pdf'


theme:
    name: readthedocs
