site_name: 2020_5BI_Team5

nav:
    - 'Project Charter': 'charter01.md'
    - 'Software Requirements Specification': 'Software_Requirements_Specification.md'
    - 'Software Project Management Plan': 'project_management.md'
   
    
theme:
    name: readthedocs

