site_name: 2020_5BI_Team5

nav:
    - 'Project Charter': 'charter01.md'
    - 'Software Requirements Specification': 'Software_Requirements_Specification.md'
    - 'Software Project Management Plan': 'project_management.md'
    - 'Test Case Specification': 'test_case_specification.md'
    - 'Business model canvas': 'business_model_canvas-team5.pdf'
    - 'Project model canvas': 'Project_Model_Canvas-team5.pdf'
    - 'Project Success Criteria': 'Project_Success_Criteria.md'
    - 'User Guide': 'User_Guide.md'
    - 'Architecture and design': 'Architecture_And_Design.md'
    - 'iteration plan': 'iteration_plan.md'
    - 'release plan': 'release_plan.md'
    - 'System Documentation': 'System_Documentation.md'
<<<<<<< HEAD
    - 'Memo of undestanding': 'Memo_of_understanding.md'
=======
    - 'Memo of understanding': 'Memo_of_understanding.md'
>>>>>>> 603837677da452027f0b64bdd1403195ee93989c


theme:
    name: readthedocs
